ARG BASE_IMAGE=
FROM ${BASE_IMAGE}

ENV TZ=UTC \
    URL_FETCH_IGNORE_CERTS=1 \
    HOME_ROOT=/config \
    HOME_USER=/config

COPY ./release.tar.gz /tmp
RUN tar xzf /tmp/release.tar.gz -C / && /etc/warpcode/install.sh && rm -f /tmp/release.tar.gz

RUN run-app -e -- s6-printenv

WORKDIR /data
ENTRYPOINT ["/entrypoint"]
