ARG BASE_IMAGE=
FROM ${BASE_IMAGE}

ENV TZ=UTC \
    URL_FETCH_IGNORE_CERTS=1

COPY ./release.tar.gz /tmp
RUN tar xzf /tmp/release.tar.gz -C / && /etc/warpcode/install.sh && rm -f /tmp/release.tar.gz

ENTRYPOINT ["/entrypoint"]
