ARG BASE_IMAGE=
ARG BASE_TAG=
FROM ${BASE_IMAGE}:${BASE_TAG}

RUN apk add --no-cache \
        su-exec

ENV TZ=Europe/London \
    PUID=911 \
    PGID=911

COPY ./rootfs/ /

RUN addgroup -g "$PGID" docker \
    && adduser \
    --home "/home/docker" \
    --disabled-password \
    --gecos "" \
    --ingroup "docker" \
    --no-create-home \
    --uid "$PUID" \
    "docker" \
     && mkdir -p /home/docker \
     && chown -R docker:docker /home/docker
