ARG BASE_IMAGE=
ARG BASE_TAG=

FROM ${BASE_IMAGE}:${BASE_TAG}

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/London \
    PUID=911 \
    PGID=911 \
    S6_VERSION=v2.1.0.2

COPY ./rootfs/ /
RUN /etc/warpcode/setup/setup_default_user.sh \
    && /etc/warpcode/setup/install_base_packages.sh \
    && /etc/warpcode/setup/install_s6.sh

ENTRYPOINT ["/init"]
