#!/usr/bin/with-contenv sh

usermod -o -u "${PUID}" app >/dev/null 2>&1
groupmod -o -g "${PGID}" app >/dev/null 2>&1

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u app)
User gid:    $(id -g app)
-------------------------------------
"
