#!/usr/bin/with-contenv sh

usermod -o -u "${PUID}" docker >/dev/null 2>&1
groupmod -o -g "${PGID}" docker >/dev/null 2>&1

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u docker)
User gid:    $(id -g docker)
-------------------------------------
"
