name: Build the image

on:
  push:
    branches: master
    paths:
      - versions/*
      - Dockerfile.*
      - rootfs/**
      - build*
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - name: Build the base images
        run: |
          bash build-all.sh --build prod
