name: Test image builds

on:
  push:
    branches: master
    paths:
      - Dockerfile.*
      - rootfs/**
      - Makefile

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build the base images
        run: |
          make build-test-alpine-edge
