name: Build the image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build the alpine:latest image
        run: |
          docker buildx build \
            --pull \
            -f Dockerfile.alpine
            -t warpcode/alpine:latest \
            --platform linux/amd64,linux/arm,linux/arm64 .
      - name: Build the debian:latest image
        run: |
          docker buildx build \
            --pull \
            -f Dockerfile.debian
            -t warpcode/debian:latest \
            --platform linux/amd64,linux/arm,linux/arm64 .
